### ISSUE TITLE
Manifest not being added to distFiles

### ISSUE THREAD

**Issue by rmachielse** [arenoir/ember-cli-deploy-html-manifest#1]
This plugin doesn't seem to add the appcache file to distFiles, causing it not to be processed by other plugins. The didPrepare method should return `{ distFiles: [filename] }` or something so the rest of the deploy process knows about the file. I had to override distFiles for each plugin manually in `config/deploy.js` to fix this. Is there a reason for leaving this out?

Also, the `manifestRoot` doesn't make a lot of sense, since you can't let de manifest be created in `revisions/revisionKey` right?

**Comment by arenoir** [comment]
@rmachielse so the `didPrepare` hook should return a promise that returns the `distFiles` array, I will add that to my todo list.  Do I push the appcache file to an existing array or is this a new array?

The `manifestRoot` is used when adding the manifest attribute to the index.html page.  It should match the directory where you upload the manifest file.  It is designed to match the `uploadDestination` of the [ssh2](https://github.com/arenoir/ember-cli-deploy-ssh2) addon used to perform uploading and activation.  

This plugin "html-manifest" is only responsible for creating the manifest and updating the index.html page.

**Comment by rmachielse** [comment]
Hi @arenoir, according to the [documentation](http://ember-cli.com/ember-cli-deploy/docs/v0.5.x/writing-a-plugin/) it should be possible to return (or resolve with a promise) an object with `distFiles`. You don't have to append, it can be a new array indeed.

I see how the `manifestRoot` makes sense in that case, however with s3 this is not possible. It doesn't matter anyway as it's overridable, it's just that I override it to be empty.

**Comment by arenoir** [comment]
Fixed in version 0.0.4
